# Site
title: Microbiologia para Artistas
subtitle: Bioprototipagem com propósito

# URL
url: http://
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4443
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
